src/Countries/US/Medicare.php
=> Fix spelling

src/Countries/US/Alabama/AlabamaIncome.php, src/Traits/WithDependents.php, src/Traits/WithExemptions.php, src/Traits/WithPersonalExemption.php, tests/Unit/Countries/US/Alabama/AlabamaIncomeTest.php, tests/Unit/Countries/US/FederalIncomeTest.php
Adds the option for no personal exemption (`form A4 line 1 = 0`)
=> No personal exemtption option

src/Countries/US/Medicare/V20170101/Medicare.php, tests/Unit/Countries/US/Alabama/AlabamaUnemploymentTest.php, tests/Unit/Countries/US/FederalUnemploymentTest.php, tests/Unit/Countries/US/MedicareTest.php, tests/Unit/Countries/US/SocialSecurityTest.php, tests/Unit/TaxesTest.php
- Fix additional tax calculation on Medicare
- Add tests to make sure this type of bug didn't affect any other tax classes (it didn't)
=> Fix bug and add some tests

src/Countries/US/Alabama/AlabamaIncome/V20180101/AlabamaIncome.php, tests/Unit/Countries/US/Alabama/AlabamaIncomeTest.php
I missed upping the head of household and single deductions as well.
=> Alabama taxes 2018

src/Classes/BaseIncome.php, src/Classes/BaseStateUnemployment.php, src/Classes/BaseTax.php, src/Classes/TaxResults.php, src/Classes/Taxes.php, src/Countries/US/Alabama/AlabamaUnemployment/V20170101/AlabamaUnemployment.php, src/Countries/US/FederalUnemployment/BaseStateUnemployment.php, src/Countries/US/Georgia/GeorgiaUnemployment/V20180101/GeorgiaUnemployment.php, tests/Unit/TaxResultsTest.php
We need this so we can figure out the wage buckets for each type of tax. I also made the code a little bit more DRY.
=> Add ability to get adjusted earnings

src/Countries/US/Georgia/GeorgiaIncome/V20180101/GeorgiaIncome.php, tests/Unit/Countries/US/Georgia/GeorgiaIncomeTest.php, tests/Unit/TaxesTest.php
Just doubling them per: 
https://github.com/spurjobs/Spur-Money-Inc/issues/300
=> Change Georgia standard deduction

src/Classes/BaseTax.php, src/Classes/Taxes.php, src/Countries/US/Medicare/Medicare.php, src/Countries/US/SocialSecurity/SocialSecurity.php, tests/Unit/Countries/US/FederalIncomeTest.php, tests/Unit/TaxesTest.php
**Story**
https://github.com/spurjobs/Spur-Money-Inc/issues/572
**Description**
sortBy PRIORITY const on tax class.  default is 9999 for all taxes
=> money-572 fica taxes first

src/Countries/US/Arizona/ArizonaIncome/V20180101/ArizonaIncome.php, src/Countries/US/Colorado/ColoradoIncome/V20180101/ColoradoIncome.php, src/Countries/US/Georgia/GeorgiaIncome/V20180101/GeorgiaIncome.php, src/Countries/US/NewMexico/NewMexicoIncome/V20180101/NewMexicoIncome.php, src/Countries/US/NorthCarolina/NorthCarolinaIncome/V20180101/NorthCarolinaIncome.php, src/Countries/US/Wisconsin/WisconsinIncome/V20180101/WisconsinIncome.php, tests/Unit/Countries/US/Arizona/ArizonaIncomeTest.php, tests/Unit/Countries/US/Colorado/ColoradoIncomeTest.php, tests/Unit/Countries/US/Georgia/GeorgiaIncomeTest.php, tests/Unit/Countries/US/NewMexico/NewMexicoIncomeTest.php, tests/Unit/Countries/US/NorthCarolina/NorthCarolinaIncomeTest.php, tests/Unit/Countries/US/Wisconsin/WisconsinIncomeTest.php, tests/Unit/TaxesTest.php
https://github.com/spurjobs/Spur-Money-Inc/issues/722
=> Fix incorrect deductions

src/Countries/US/Georgia/GeorgiaIncome/V20180101/GeorgiaIncome.php, tests/Unit/Countries/US/Georgia/GeorgiaIncomeTest.php, tests/Unit/TaxesTest.php
https://github.com/spurjobs/Spur-Money-Inc/issues/748
=> Update GA deductions

.env.example, .gitignore, phpunit.xml, src/migrations/2017_01_01_000000_create_governmental_unit_areas_table.php, tests/TestCase.php
Removed the hard coded config settings inside phpunit.xml file and moved them into the .env
=> Convert phpxml config to .env

src/Countries/US/SocialSecurity/V20190101/SocialSecurity.php, src/Countries/US/SocialSecurity/V20190101/SocialSecurityEmployer.php, tests/Unit/Countries/US/SocialSecurityTest.php
https://github.com/spurjobs/Spur-Money-Inc/issues/874
=> Add 2019 Social Security changes

src/Countries/US/FederalIncome/V20190101/FederalIncome.php, tests/Unit/Countries/US/FederalIncome/V20170101/FederalIncomeTest.php, tests/Unit/Countries/US/FederalIncome/V20180101/FederalIncomeTest.php, tests/Unit/Countries/US/FederalIncome/V20190101/FederalIncomeTest.php
https://github.com/spurjobs/Spur-Money-Inc/issues/876
Prolly a good idea to spot check the numbers since this will affect ever single worker and every single paycheck.
=> 2019 Fed Inc changes

src/Countries/US/Georgia/GeorgiaIncome/V20190101/GeorgiaIncome.php, tests/Unit/Countries/US/Georgia/GeorgiaIncome/V20180101/GeorgiaIncomeTest.php, tests/Unit/Countries/US/Georgia/GeorgiaIncome/V20190101/GeorgiaIncomeTest.php
https://github.com/spurjobs/Spur-Money-Inc/issues/872
=> 2019 Georgia Income Changes

src/Countries/US/Georgia/GeorgiaIncome/V20190101/GeorgiaIncome.php, tests/Unit/Countries/US/Georgia/GeorgiaIncome/V20190101/GeorgiaIncomeTest.php
Updated Standard Deductions
https://github.com/spurjobs/Spur-Money-Inc/issues/872
=> Bug - Georgia 2019 standard deductions

src/Countries/US/Georgia/GeorgiaIncome/V20190101/GeorgiaIncome.php, tests/Unit/Countries/US/Georgia/GeorgiaIncome/V20190101/GeorgiaIncomeTest.php
https://github.com/spurjobs/Spur-Money-Inc/issues/872
=> Fix 2019 Georgia deduction amount

src/Classes/Payroll.php, src/Classes/Taxes.php, src/Countries/US/NewYork/NewYorkFamilyMedicalLeave/NewYorkFamilyMedicalLeave.php, src/Countries/US/NewYork/NewYorkFamilyMedicalLeave/V20190101/NewYorkFamilyMedicalLeave.php, src/Providers/TaxServiceProvider.php, src/migrations/2019_02_04_000000_insert_new_york_family_medical_leave_tax.php, tests/Unit/Countries/US/NewYork/NewYorkFamilyMedicalLeaveTest.php
https://github.com/spurjobs/Spur-Money-Inc/issues/973
=> Add NY FML

src/Countries/US/NewYork/NewYorkDisabilityInsurance/NewYorkDisabilityInsurance.php, src/Countries/US/NewYork/NewYorkDisabilityInsurance/V20190101/NewYorkDisabilityInsurance.php, src/Providers/TaxServiceProvider.php, src/migrations/2019_02_07_000000_insert_new_york_disability_insurance_tax.php, tests/Unit/Countries/US/NewYork/NewYorkDisabilityInsuranceTest.php
https://github.com/spurjobs/Spur-Money-Inc/issues/974
=> Add NY DIT

src/Countries/US/Massachusetts/MassachusettsFamilyMedicalLeave/MassachusettsFamilyMedicalLeave.php, src/Countries/US/Massachusetts/MassachusettsFamilyMedicalLeave/V20190101/MassachusettsFamilyMedicalLeave.php, src/Countries/US/Massachusetts/MassachusettsFamilyMedicalLeaveEmployer/MassachusettsFamilyMedicalLeaveEmployer.php, src/Countries/US/Massachusetts/MassachusettsFamilyMedicalLeaveEmployer/V20190101/MassachusettsFamilyMedicalLeaveEmployer.php, src/Providers/TaxServiceProvider.php, src/migrations/2019_02_08_000000_insert_massachusetts_family_medical_leave_tax.php, tests/Unit/Countries/US/Massachusetts/MassachusettsFamilyMedicalLeaveEmployerTest.php, tests/Unit/Countries/US/Massachusetts/MassachusettsFamilyMedicalLeaveTest.php
https://github.com/spurjobs/Spur-Money-Inc/issues/982
=> Add MA FML tax

src/Countries/US/Kentucky/KentuckyIncome/KentuckyIncome.php, src/Countries/US/Kentucky/KentuckyIncome/V20190101/KentuckyIncome.php, src/Countries/US/Kentucky/KentuckyUnemployment/KentuckyUnemployment.php, src/Countries/US/Kentucky/KentuckyUnemployment/V20190101/KentuckyUnemployment.php, src/Models/Countries/US/Kentucky/KentuckyIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/migrations/2019_03_20_162120_create_kentucky_income_tax_information.php, tests/TestCase.php, tests/Unit/Countries/US/Kentucky/KentuckyIncomeTest.php, tests/Unit/Countries/US/Kentucky/KentuckyUnemploymentTest.php
Implement Kentucky income and unemployment taxes
https://spurjob.atlassian.net/browse/ACC-8
=> feature_acc-8_ky-new-state

src/Models/Countries/US/Maryland/MarylandIncomeTaxInformation.php
https://spurjob.atlassian.net/browse/ACC-7
forgot a method
=> acc-7 add getTax()

src/Countries/US/Maryland/MarylandIncome/V20190101/MarylandIncome.php
https://spurjob.atlassian.net/browse/ACC-7
fix Maryland work in Deleware income tax bracket bug
=> acc-7 fix md income tax bug

src/Countries/US/Kentucky/JeffersonCounty/V20190101/JeffersonCounty.php, src/migrations/2019_05_21_000001_insert_jefferson_county_ky_tax.php, tests/Unit/Countries/US/Kentucky/JeffersonCountyTest.php
refs: https://spurjob.atlassian.net/browse/ACC-191
=> ACC-191 Ky local taxes fix

src/Countries/US/Louisiana/LouisianaIncome/LouisianaIncome.php, src/Countries/US/Louisiana/LouisianaIncome/V20190101/LouisianaIncome.php, src/Countries/US/Louisiana/LouisianaUnemployment/LouisianaUnemployment.php, src/Countries/US/Louisiana/LouisianaUnemployment/V20190101/LouisianaUnemployment.php, src/Models/Countries/US/Louisiana/LouisianaIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_06_05_000001_add_louisiana_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/Louisiana/LouisianaIncomeTest.php, tests/Unit/Countries/US/Louisiana/LouisianaUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-246
This is the formula to calculate the state taxes. Took me the most time to ensure that I had the grouping correct.
These are the examples from the pdf that I used as a key, some of Tasie's test cases were the wrong values which I proved by doing them by hand. For all of the tests in the LouisianaIncomeTest class I verified by hand to ensure they were correct.
=> ACC-246 LA state tax 

src/Classes/Payroll.php, src/Countries/US/Oklahoma/OklahomaIncome/OklahomaIncome.php, src/Countries/US/Oklahoma/OklahomaIncome/V20190101/OklahomaIncome.php, src/Countries/US/Oklahoma/OklahomaUnemployment/OklahomaUnemployment.php, src/Countries/US/Oklahoma/OklahomaUnemployment/V20190101/OklahomaUnemployment.php, src/Models/Countries/US/Oklahoma/OklahomaIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_09_19_000000_add_oklahoma_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/Oklahoma/OklahomaIncomeTest.php, tests/Unit/Countries/US/Oklahoma/OklahomaUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-250
=> ACC-250 OK state tax setup

src/Countries/US/California/CaliforniaIncome/CaliforniaIncome.php, src/Countries/US/California/CaliforniaIncome/V20190101/CaliforniaIncome.php, src/Countries/US/California/CaliforniaUnemployment/CaliforniaUnemployment.php, src/Countries/US/California/CaliforniaUnemployment/V20190101/CaliforniaUnemployment.php, src/Models/Countries/US/California/CaliforniaIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_06_26_000000_add_california_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/California/CaliforniaIncomeTaxTest.php, tests/Unit/Countries/US/California/CaliforniaUnemploymentTest.php
[New State: California Setup/SIT/SUTA](https://spurjob.atlassian.net/browse/ACC-125)
=> feature/ACC-125 - Implement CA state taxes/unemployment

tests/Unit/Countries/US/California/CaliforniaIncomeTaxTest.php, tests/Unit/Countries/US/California/CaliforniaUnemploymentTest.php, tests/Unit/Countries/US/Nevada/NevadaUnemploymentTest.php, tests/Unit/Countries/US/WestVirginia/WestVirginiaUnemploymentTest.php
Fix tests for $0 vs null taxes
=> feature/ACC-125; feature/ACC-253; feature/ACC-128 - fix tests

src/migrations/2019_06_21_000000_insert_new_jersey_additional_employee_deductions.php
refs: https://spurjob.atlassian.net/browse/ACC-223
Cannot get the NJ deductions to show up when running payroll. Just trying something with this.
=> ACC-223 Remove home from migration

src/Countries/US/California/CaliforniaDisabilityInsurance/CaliforniaDisabilityInsurance.php, src/Countries/US/California/CaliforniaDisabilityInsurance/V20190101/CaliforniaDisabilityInsurance.php, src/Providers/TaxServiceProvider.php, src/migrations/2019_07_10_000000_add_california_disability_insurance.php, tests/Unit/Countries/US/California/CaliforniaDisabilityInsuranceTest.php
refs: https://spurjob.atlassian.net/browse/ACC-267
=> ACC-267 CA add disability insurance

src/Countries/US/California/CaliforniaDisabilityInsurance/CaliforniaDisabilityInsurance.php, src/Countries/US/California/CaliforniaDisabilityInsurance/V20190101/CaliforniaDisabilityInsurance.php, src/Providers/TaxServiceProvider.php, src/migrations/2019_07_12_000000_add_california_disability_insurance.php, tests/Unit/Countries/US/California/CaliforniaDisabilityInsuranceTest.php
refs: https://spurjob.atlassian.net/browse/ACC-267
So I messed up the last PR. Here's what I did. I accidentally made the employment training branch off of the disability insurance branch. In the new branch I deleted the disability insurance changes that were in the new branch. Fast forward to merging the employment training branch and when I merged it, it merged the the disability insurance pr too and that caused all the changes in the disability insurance branch to get deleted. So these are the changes that need to be in for the ca disability insurance. You can see on the screen shot that it adds the disability insurance files then deletes them.
=> ACC-267 California Disability Insurance 2 

src/migrations/2019_07_12_000000_remove_kentucky_fayette_county_tax.php
[KY: Local Taxes - % with no Wage Cap](https://spurjob.atlassian.net/browse/ACC-263)
* Remove Fayette County tax as that geo region was just to be used for the Fayette County Public Schools tax
=> ACC-263 - 

src/Countries/US/California/CaliforniaEmploymentTrainingTax/CaliforniaEmploymentTrainingTax.php
refs: https://spurjob.atlassian.net/browse/ACC-268
**I Need to learn how to read, and understand what I am reading.**
=> ACC-268 Ca Employment Training is a liability not a deduction

src/Classes/BaseTax.php, src/Countries/US/California/CaliforniaDisabilityInsurance/V20190101/CaliforniaDisabilityInsurance.php, src/Countries/US/California/CaliforniaEmploymentTrainingTax/V20190101/CaliforniaEmploymentTrainingTax.php, src/Countries/US/NewJersey/NewJerseyDisabilityInsurance/V20190101/NewJerseyDisabilityInsurance.php, src/Countries/US/NewJersey/NewJerseyFamilyMedicalLeave/V20190101/NewJerseyFamilyMedicalLeave.php, src/Countries/US/NewJersey/NewJerseyUnemploymentInsurance/V20190101/NewJerseyUnemploymentInsurance.php
refs: https://spurjob.atlassian.net/browse/ACC-305
=> ACC-305 Remove unneeded getBaseEarningsWageBase function

src/Countries/US/Kentucky/FlorenceCity/V20190101/FlorenceCity.php, tests/Unit/Countries/US/Kentucky/FlorenceCityTest.php
https://spurjob.atlassian.net/browse/ACC-193
=> Add YTD limit for ACC-193

src/Countries/US/Pennsylvania/PennsylvaniaIncome/PennsylvaniaIncome.php, src/Countries/US/Pennsylvania/PennsylvaniaIncome/V20190101/PennsylvaniaIncome.php, src/Countries/US/Pennsylvania/PennsylvaniaUnemployment/PennsylvaniaUnemployment.php, src/Countries/US/Pennsylvania/PennsylvaniaUnemployment/V20190101/PennsylvaniaUnemployment.php, src/Models/Countries/US/Pennsylvania/PennsylvaniaIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_07_25_000000_add_pennsylvania_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/Pennsylvania/PennsylvaniaIncomeTest.php, tests/Unit/Countries/US/Pennsylvania/PennsylvaniaUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-137
=> ACC-137 New State: Pennsylvania Setup/SIT/SUTA

src/Countries/US/WestVirginia/CharlestonCityServiceFee/V20190101/CharlestonCityServiceFee.php, src/Countries/US/WestVirginia/FairmontCityServiceFee/V20190101/FairmontCityServiceFee.php, src/Countries/US/WestVirginia/HuntingtonCityServiceFee/V20190101/HuntingtonCityServiceFee.php, src/Countries/US/WestVirginia/MorgantownCityServiceFee/V20190101/MorgantownCityServiceFee.php, src/Countries/US/WestVirginia/ParkersburgCityServiceFee/V20190101/ParkersburgCityServiceFee.php
* use governmental unit area for week to date
=> ACC-283 wv local taxes

.travis.yml, src/Countries/US/Kansas/KansasIncome/KansasIncome.php, src/Countries/US/Kansas/KansasIncome/V20190101/KansasIncome.php, src/Countries/US/Kansas/KansasUnemployment/KansasUnemployment.php, src/Countries/US/Kansas/KansasUnemployment/V20190101/KansasUnemployment.php, src/Models/Countries/US/Kansas/KansasIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_08_01_000000_add_kansas_income_tax_information.php, tests/TestCase.php, tests/Unit/Countries/US/Alabama/AlabamaUnemploymentTest.php, tests/Unit/Countries/US/FederalIncome/V20170101/FederalIncomeTest.php, tests/Unit/Countries/US/FederalIncome/V20180101/FederalIncomeTest.php, tests/Unit/Countries/US/FederalUnemploymentTest.php, tests/Unit/Countries/US/Florida/FloridaUnemploymentTest.php, tests/Unit/Countries/US/Georgia/GeorgiaUnemploymentTest.php, tests/Unit/Countries/US/Kansas/KansasIncomeTest.php, tests/Unit/Countries/US/Kansas/KansasUnemploymentTest.php, tests/Unit/Countries/US/MedicareTest.php, tests/Unit/Countries/US/NorthCarolina/NorthCarolinaUnemployment/V20180101/NorthCarolinaUnemploymentTest.php, tests/Unit/Countries/US/SocialSecurity/V20170101/SocialSecurityEmployerTest.php, tests/Unit/Countries/US/SocialSecurity/V20170101/SocialSecurityTest.php, tests/Unit/Countries/US/SocialSecurity/V20180101/SocialSecurityEmployerTest.php, tests/Unit/Countries/US/SocialSecurity/V20180101/SocialSecurityTest.php, tests/Unit/Countries/US/Texas/TexasUnemploymentTest.php
[New State: Kansas Setup/SIT/SUTA](https://spurjob.atlassian.net/browse/ACC-314)
* Implement KS state tax/unemployment
* Remove 'us' test case location since that was actually KS
* update test locations
=> ACC-314 - Implement KS state tax/unemployment

src/Countries/US/Mississippi/MississippiIncome/MississippiIncome.php
refs: https://spurjob.atlassian.net/browse/ACC-345
=> ACC-345 MississippiIncome class error

src/Classes/Payroll.php, src/Countries/US/NewYork/NewYorkDisabilityInsurance/V20190101/NewYorkDisabilityInsurance.php, src/Countries/US/NewYork/NewYorkFamilyMedicalLeave/V20190101/NewYorkFamilyMedicalLeave.php, tests/Unit/Countries/US/NewYork/NewYorkDisabilityInsuranceTest.php, tests/Unit/Countries/US/NewYork/NewYorkFamilyMedicalLeaveTest.php
https://spurjob.atlassian.net/browse/ACC-368
use the wtd method
=> ACC-368 use method for wtd earnings

src/Countries/US/SouthCarolina/SouthCarolinaIncome/SouthCarolinaIncome.php, src/Countries/US/SouthCarolina/SouthCarolinaIncome/V20190101/SouthCarolinaIncome.php, src/Countries/US/SouthCarolina/SouthCarolinaUnemployment/SouthCarolinaUnemployment.php, src/Countries/US/SouthCarolina/SouthCarolinaUnemployment/V20190101/SouthCarolinaUnemployment.php, src/Models/Countries/US/SouthCarolina/SouthCarolinaIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_08_15_000000_add_south_carolina_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/SouthCarolina/SouthCarolinaIncomeTest.php, tests/Unit/Countries/US/SouthCarolina/SouthCarolinaUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-346
=> ACC-346 New State: South Carolina Setup/SIT/SUTA

src/Countries/US/Ohio/Dayton/V20190101/Dayton.php, tests/Unit/Countries/US/Ohio/DaytonTest.php
=> ACC-325: fix age for Dayton

src/Countries/US/Maine/MaineIncome/MaineIncome.php, src/Countries/US/Maine/MaineIncome/V20190101/MaineIncome.php, src/Countries/US/Maine/MaineUnemployment/MaineUnemployment.php, src/Countries/US/Maine/MaineUnemployment/V20190101/MaineUnemployment.php, src/Models/Countries/US/Maine/MaineIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_08_22_100000_add_maine_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/Maine/MaineIncomeTest.php, tests/Unit/Countries/US/Maine/MaineUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-337
=> ACC-337 New State: Maine Setup/SIT/SUTA

src/Countries/US/NorthDakota/NorthDakotaIncome/NorthDakotaIncome.php, src/Countries/US/NorthDakota/NorthDakotaIncome/V20190101/NorthDakotaIncome.php, src/Countries/US/NorthDakota/NorthDakotaUnemployment/NorthDakotaUnemployment.php, src/Countries/US/NorthDakota/NorthDakotaUnemployment/V20190101/NorthDakotaUnemployment.php, src/Models/Countries/US/NorthDakota/NorthDakotaIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_08_29_000001_add_north_dakota_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/NorthDakota/NorthDakotaIncomeTest.php, tests/Unit/Countries/US/NorthDakota/NorthDakotaUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-343
=> ACC-343 New State: North Dakota Setup/SIT/SUTA

src/Countries/US/Utah/UtahIncome/UtahIncome.php, src/Countries/US/Utah/UtahIncome/V20190101/UtahIncome.php, src/Countries/US/Utah/UtahUnemployment/UtahUnemployment.php, src/Countries/US/Utah/UtahUnemployment/V20190101/UtahUnemployment.php, src/Models/Countries/US/Utah/UtahIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_08_29_000002_add_utah_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/Utah/UtahIncomeTest.php, tests/Unit/Countries/US/Utah/UtahUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-348
=> ACC-348 New State: Utah Setup/SIT/SUTA

src/Countries/US/Washington/WashingtonUnemployment/V20190101/WashingtonUnemployment.php, src/Countries/US/Washington/WashingtonUnemployment/WashingtonUnemployment.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_09_09_000000_add_washington_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/Washington/WashingtonUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-400
=> ACC-400 New State: Washington Setup/SUTA

src/Countries/US/NewHampshire/NewHampshireUnemployment/NewHampshireUnemployment.php, src/Countries/US/NewHampshire/NewHampshireUnemployment/V20190101/NewHampshireUnemployment.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_09_09_000001_add_new_hampshire_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/NewHampshire/NewHampshireUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-401
=> ACC-401 New State: New Hampshire Setup/SUTA

src/Countries/US/Wyoming/WyomingUnemployment/V20190101/WyomingUnemployment.php, src/Countries/US/Wyoming/WyomingUnemployment/WyomingUnemployment.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_09_13_000000_add_wyoming_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/Wyoming/WyomingUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-399
=> ACC-399 New State: Wyoming Setup/SUTA

src/Countries/US/RhodeIsland/RhodeIslandIncome/RhodeIslandIncome.php, src/Countries/US/RhodeIsland/RhodeIslandIncome/V20190101/RhodeIslandIncome.php, src/Countries/US/RhodeIsland/RhodeIslandUnemployment/RhodeIslandUnemployment.php, src/Countries/US/RhodeIsland/RhodeIslandUnemployment/V20190101/RhodeIslandUnemployment.php, src/Models/Countries/US/RhodeIsland/RhodeIslandIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_09_14_000000_add_rhode_island_income_tax_information_table.php, tests/TestCase.php, tests/Unit/Countries/US/RhodeIsland/RhodeIslandIncomeTest.php, tests/Unit/Countries/US/RhodeIsland/RhodeIslandUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-392
=> ACC-392 New State: Rhode Island Setup/SIT/SUTA

src/Countries/US/Hawaii/HawaiiIncome/HawaiiIncome.php, src/Countries/US/Hawaii/HawaiiIncome/V20190101/HawaiiIncome.php, src/Countries/US/Hawaii/HawaiiUnemployment/HawaiiUnemployment.php, src/Countries/US/Hawaii/HawaiiUnemployment/V20190101/HawaiiUnemployment.php, src/Models/Countries/US/Hawaii/HawaiiIncomeTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/config/config.php, src/migrations/2019_09_16_000000_add_hawaii_income_tax_information.php.php, tests/TestCase.php, tests/Unit/Countries/US/Hawaii/HawaiiIncomeTest.php, tests/Unit/Countries/US/Hawaii/HawaiiUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-389
=> ACC-389 New State: Hawaii Setup/SIT/SUTA

src/Countries/US/Colorado/AuroraOccupationalPrivilege/V20180101/AuroraOccupationalPrivilege.php, src/Countries/US/Colorado/AuroraOccupationalPrivilege/V20190101/AuroraOccupationalPrivilege.php, src/Countries/US/Colorado/AuroraOccupationalPrivilegeEmployer/V20180101/AuroraOccupationalPrivilegeEmployer.php, src/Countries/US/Colorado/AuroraOccupationalPrivilegeEmployer/V20190101/AuroraOccupationalPrivilegeEmployer.php, src/Countries/US/Colorado/ColoradoLocalIncome.php, src/Countries/US/Colorado/DenverOccupationalPrivilege/V20180101/DenverOccupationalPrivilege.php, src/Countries/US/Colorado/DenverOccupationalPrivilege/V20190101/DenverOccupationalPrivilege.php, src/Countries/US/Colorado/DenverOccupationalPrivilegeEmployer/V20180101/DenverOccupationalPrivilegeEmployer.php, src/Countries/US/Colorado/DenverOccupationalPrivilegeEmployer/V20190101/DenverOccupationalPrivilegeEmployer.php, src/Countries/US/Colorado/GlendaleOccupationalPrivilege/V20180101/GlendaleOccupationalPrivilege.php, src/Countries/US/Colorado/GlendaleOccupationalPrivilege/V20190101/GlendaleOccupationalPrivilege.php, src/Countries/US/Colorado/GlendaleOccupationalPrivilegeEmployer/V20180101/GlendaleOccupationalPrivilegeEmployer.php, src/Countries/US/Colorado/GlendaleOccupationalPrivilegeEmployer/V20190101/GlendaleOccupationalPrivilegeEmployer.php, src/Countries/US/Colorado/GreenwoodVillageOccupationalPrivilege/V20180101/GreenwoodVillageOccupationalPrivilege.php, src/Countries/US/Colorado/GreenwoodVillageOccupationalPrivilege/V20190101/GreenwoodVillageOccupationalPrivilege.php, src/Countries/US/Colorado/GreenwoodVillageOccupationalPrivilegeEmployer/V20180101/GreenwoodVillageOccupationalPrivilegeEmployer.php, src/Countries/US/Colorado/GreenwoodVillageOccupationalPrivilegeEmployer/V20190101/GreenwoodVillageOccupationalPrivilegeEmployer.php, src/Countries/US/Colorado/SheridanOccupationalPrivilege/V20180101/SheridanOccupationalPrivilege.php, src/Countries/US/Colorado/SheridanOccupationalPrivilege/V20190101/SheridanOccupationalPrivilege.php, src/Countries/US/Colorado/SheridanOccupationalPrivilegeEmployer/V20180101/SheridanOccupationalPrivilegeEmployer.php, src/Countries/US/Colorado/SheridanOccupationalPrivilegeEmployer/V20190101/SheridanOccupationalPrivilegeEmployer.php, tests/Unit/Countries/US/Colorado/V20190101/AuroraOccupationalPrivilegeEmployerTest.php, tests/Unit/Countries/US/Colorado/V20190101/DenverOccupationalPrivilegeEmployerTest.php, tests/Unit/Countries/US/Colorado/V20190101/DenverOccupationalPrivilegeTest.php, tests/Unit/Countries/US/Colorado/V20190101/GlendaleOccupationalPrivilegeEmployerTest.php, tests/Unit/Countries/US/Colorado/V20190101/GlendaleOccupationalPrivilegeTest.php, tests/Unit/Countries/US/Colorado/V20190101/GreenwoodVillageOccupationalPrivilegeEmployerTest.php, tests/Unit/Countries/US/Colorado/V20190101/GreenwoodVillageOccupationalPrivilegeTest.php, tests/Unit/Countries/US/Colorado/V20190101/SheridanOccupationalPrivilegeEmployerTest.php, tests/Unit/Countries/US/Colorado/V20190101/SheridanOccupationalPrivilegeTest.php
[Local Taxes: MTD does not convert to dollars](https://spurjob.atlassian.net/browse/ACC-447)
* change Colorado local month wage amounts to dollars
=> ACC-447: change month wage amounts to dollars

src/Countries/US/Virginia/VirginiaIncome/V20190101/VirginiaIncome.php, src/Countries/US/Virginia/VirginiaIncome/V20190701/VirginiaIncome.php, tests/Unit/Countries/US/Virginia/VirginiaIncomeTest.php
refs: https://spurjob.atlassian.net/browse/ACC-414
=> ACC-414 VA: Update Standard Deduction

src/Countries/US/Oregon/OregonTransit/OregonTransit.php, src/Countries/US/Oregon/OregonTransit/V20190701/OregonTransit.php, src/Providers/TaxServiceProvider.php, src/migrations/2019_09_30_000000_add_oregon_transit_tax.php, tests/Unit/Countries/US/Oregon/OregonIncomeTest.php, tests/Unit/Countries/US/Oregon/OregonTransitTest.php, tests/Unit/Countries/US/Oregon/OregonUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/ACC-433
=> ACC-433 Oregon: State Transit Tax

src/Countries/US/Alaska/AlaskaUnemployment/V20190101/AlaskaUnemployment.php, src/Countries/US/Connecticut/ConnecticutUnemployment/V20190101/ConnecticutUnemployment.php, src/Countries/US/Delaware/DelawareUnemployment/V20190101/DelawareUnemployment.php, src/Countries/US/Hawaii/HawaiiUnemployment/V20190101/HawaiiUnemployment.php, src/Countries/US/Idaho/IdahoUnemployment/V20190101/IdahoUnemployment.php, src/Countries/US/Iowa/IowaUnemployment/V20190101/IowaUnemployment.php, src/Countries/US/Louisiana/LouisianaUnemployment/V20190101/LouisianaUnemployment.php, src/Countries/US/Maine/MaineUnemployment/V20190101/MaineUnemployment.php, src/Countries/US/Minnesota/MinnesotaUnemployment/V20190101/MinnesotaUnemployment.php, src/Countries/US/Mississippi/MississippiUnemployment/V20190101/MississippiUnemployment.php, src/Countries/US/Missouri/MissouriUnemployment/V20190101/MissouriUnemployment.php, src/Countries/US/Montana/MontanaUnemployment/V20190101/MontanaUnemployment.php, src/Countries/US/Nebraska/NebraskaUnemployment/V20190101/NebraskaUnemployment.php, src/Countries/US/NewHampshire/NewHampshireUnemployment/V20190101/NewHampshireUnemployment.php, src/Countries/US/NorthDakota/NorthDakotaUnemployment/V20190101/NorthDakotaUnemployment.php, src/Countries/US/Ohio/OhioUnemployment/V20190101/OhioUnemployment.php, src/Countries/US/Oklahoma/OklahomaUnemployment/V20190101/OklahomaUnemployment.php, src/Countries/US/Oregon/OregonUnemployment/V20190101/OregonUnemployment.php, src/Countries/US/Pennsylvania/PennsylvaniaUnemployment/V20190101/PennsylvaniaUnemployment.php, src/Countries/US/RhodeIsland/RhodeIslandUnemployment/V20190101/RhodeIslandUnemployment.php, src/Countries/US/SouthCarolina/SouthCarolinaUnemployment/V20190101/SouthCarolinaUnemployment.php, src/Countries/US/SouthDakota/SouthDakotaUnemployment/V20190101/SouthDakotaUnemployment.php, src/Countries/US/Utah/UtahUnemployment/V20190101/UtahUnemployment.php, src/Countries/US/Washington/WashingtonUnemployment/V20190101/WashingtonUnemployment.php, src/Countries/US/WashingtonDC/WashingtonDCUnemployment/V20190101/WashingtonDCUnemployment.php, src/Countries/US/Wyoming/WyomingUnemployment/V20190101/WyomingUnemployment.php
https://spurjob.atlassian.net/browse/ACC-460
=> ACC-460 update FUTA credit rates

src/Countries/US/Indiana/ClayIncome/V20191001/ClayIncome.php, src/Countries/US/Indiana/ClintonIncome/V20191001/ClintonIncome.php, src/Countries/US/Indiana/DuboisIncome/V20191001/DuboisIncome.php, src/Countries/US/Indiana/FayetteIncome/V20191001/FayetteIncome.php, src/Countries/US/Indiana/GreeneIncome/V20191001/GreeneIncome.php, src/Countries/US/Indiana/HancockIncome/V20191001/HancockIncome.php, src/Countries/US/Indiana/HendricksIncome/V20191001/HendricksIncome.php, src/Countries/US/Indiana/JohnsonIncome/V20191001/JohnsonIncome.php, src/Countries/US/Indiana/OhioIncome/V20191001/OhioIncome.php, src/Countries/US/Indiana/OwenIncome/V20191001/OwenIncome.php, src/Countries/US/Indiana/PutnamIncome/V20191001/PutnamIncome.php, src/Countries/US/Indiana/SullivanIncome/V20191001/SullivanIncome.php, src/Countries/US/Indiana/WhitleyIncome/V20191001/WhitleyIncome.php, tests/Unit/Countries/US/Indiana/ClayIncomeTest.php, tests/Unit/Countries/US/Indiana/ClintonIncomeTest.php, tests/Unit/Countries/US/Indiana/DuboisIncomeTest.php, tests/Unit/Countries/US/Indiana/FayetteIncomeTest.php, tests/Unit/Countries/US/Indiana/GreeneIncomeTest.php, tests/Unit/Countries/US/Indiana/HancockIncomeTest.php, tests/Unit/Countries/US/Indiana/HendricksIncomeTest.php, tests/Unit/Countries/US/Indiana/JohnsonIncomeTest.php, tests/Unit/Countries/US/Indiana/OhioIncomeTest.php, tests/Unit/Countries/US/Indiana/OwenIncomeTest.php, tests/Unit/Countries/US/Indiana/PutnamIncomeTest.php, tests/Unit/Countries/US/Indiana/SullivanIncomeTest.php, tests/Unit/Countries/US/Indiana/WhitleyIncomeTest.php
https://spurjob.atlassian.net/browse/ACC-445
=> ACC-445 update Indiana rates

src/Countries/US/Washington/WashingtonUnemployment/V20200101/WashingtonUnemployment.php, tests/Unit/Countries/US/Washington/V20200101/WashingtonUnemploymentTest.php
[Update WA SUTA Information](https://spurjob.atlassian.net/browse/ACC-524)
* Update WA SUTA wage base for 2020
=> ACC-524: update WA suta wage base for 2020

composer.lock
[Laravel Taxes Will Not Build](https://spurjob.atlassian.net/browse/ACC-583)
* regenerate composer.lock
=> ACC-583: regenerate composer.lock

src/Classes/WorkerTaxes/Payroll.php, src/Classes/WorkerTaxes/Taxes.php, src/Classes/WorkerTaxes/WageManager.php, src/Countries/US/Washington/WashingtonWorkersCompensation/V20190101/WashingtonWorkersCompensation.php, src/Countries/US/Washington/WashingtonWorkersCompensation/WashingtonWorkersCompensation.php, src/Countries/US/Washington/WashingtonWorkersCompensationEmployer/V20190101/WashingtonWorkersCompensationEmployer.php, src/Countries/US/Washington/WashingtonWorkersCompensationEmployer/WashingtonWorkersCompensationEmployer.php, src/Models/Countries/US/Washington/WashingtonWorkersCompensationTaxInformation.php, src/Providers/TaxInformationServiceProvider.php, src/Providers/TaxServiceProvider.php, src/migrations/2019_12_10_00000_insert_washington_workers_compensation_tax.php, tests/Unit/Countries/TaxTestCase.php, tests/Unit/Countries/TestParameters.php, tests/Unit/Countries/TestParametersBuilder.php, tests/Unit/Countries/US/Washington/V20190101/WashingtonWorkersCompensationEmployerTest.php, tests/Unit/Countries/US/Washington/V20190101/WashingtonWorkersCompensationTest.php, tests/Unit/TestModelCreator.php, tests/Unit/UnitTestCase.php
https://spurjob.atlassian.net/browse/ACC-526
=> ACC-526 Add WA workers comp

src/Countries/US/NewMexico/NewMexicoWorkersCompensation/NewMexicoWorkersCompensation.php, src/Countries/US/NewMexico/NewMexicoWorkersCompensation/V20190101/NewMexicoWorkersCompensation.php, src/Countries/US/NewMexico/NewMexicoWorkersCompensationEmployer/NewMexicoWorkersCompensationEmployer.php, src/Countries/US/NewMexico/NewMexicoWorkersCompensationEmployer/V20190101/NewMexicoWorkersCompensationEmployer.php, src/Providers/TaxServiceProvider.php, src/migrations/2019_12_26_00000_insert_new_mexico_workers_compensation_tax.php, tests/Unit/Countries/US/NewMexico/V20190101/NewMexicoWorkersCompensationEmployerTest.php, tests/Unit/Countries/US/NewMexico/V20190101/NewMexicoWorkersCompensationTest.php
https://spurjob.atlassian.net/browse/ACC-490
=> ACC-490 Add New Mexico Workers Compensation Tax

src/Countries/US/Oregon/SandyEmployer/V20190101/SandyEmployer.php, src/migrations/2020_01_07_000000_update_sandy_and_canby_names.php
I tried to make it easier to test and merged them in before Tasie tested them. 1 typo and 2 name changes away from being ok. I won't do that again.
=> LAWS-32 Sandy update

src/Countries/US/Oregon/WorkersCompAssessmentFund/V20190101/WorkersCompAssessmentFund.php, src/Countries/US/Oregon/WorkersCompAssessmentFund/V20200101/WorkersCompAssessmentFund.php, src/Countries/US/Oregon/WorkersCompAssessmentFund/WorkersCompAssessmentFund.php, src/Countries/US/Oregon/WorkersCompAssessmentFundEmployer/V20190101/WorkersCompAssessmentFundEmployer.php, src/Countries/US/Oregon/WorkersCompAssessmentFundEmployer/V20200101/WorkersCompAssessmentFundEmployer.php, src/Countries/US/Oregon/WorkersCompAssessmentFundEmployer/WorkersCompAssessmentFundEmployer.php, src/Providers/TaxServiceProvider.php, src/migrations/2020_01_06_00000_add_workers_comp_assessment_funds.php, tests/Unit/Countries/US/Oregon/V20200101/WorkersCompAssessmentFundEmployerTest.php, tests/Unit/Countries/US/Oregon/V20200101/WorkersCompAssessmentFundTest.php
refs: https://spurjob.atlassian.net/browse/LAWS-30
=> LAWS-30 Workers Comp Assessment Fund - Employee Deduction and Employer Liability

src/migrations/2020_01_13_000001_drop_oregon_column.php, src/migrations/2020_01_13_000002_add_oregon_column.php
If I tried to update the column type I would get errors saying I needed to use sql to do it but when I tried using raw sql I would get the same errors. I changed the column the same way on the api so I am keeping everything the same
=> LAWS-17 change oregon column

src/Countries/US/FederalIncome/V20200101/FederalIncome.php, tests/Unit/Countries/US/FederalIncome/V20200101/FederalIncomeTest.php
Margie found some bugs with the 2019 federal calcs. 
refs: https://spurjob.atlassian.net/browse/LAWS-94
=> LAWS-94 Federal taxes - fixes - 2019

src/Countries/US/FederalIncome/V20200101/FederalIncome.php, tests/Unit/Countries/US/FederalIncome/V20200101/FederalIncomeTest.php
refs: https://spurjob.atlassian.net/browse/LAWS-94
**QA Approved**
My fix yesterday wasn't quite right, now that tasie has tested the change in the release branch we found more and worked together to make the fixes, the api release still isnt in so I will get this in make a new release and update the api release with this release
=> Feature/laws 94 Federal taxes - fixes - 2019

src/Countries/US/Ohio/OhioIncome/V20190101/OhioIncome.php, src/migrations/2020_01_28_000000_add_additional_withholding_to_ohio.php, tests/Unit/Countries/US/Ohio/V20190101/OhioIncomeTest.php
So the Ohio tax form has a row about additional withholding with agreement with employer. The additional withholding wasn't on any of the Ohio calculations originally so it didn't get added. Talking with Donnie he wants to let people do additional withholding if they want to so this adds it to the db table, the Ohio income calc, and the Ohio income test
=> LAWS-11 Update ohio income tax table

src/Countries/US/SouthCarolina/SouthCarolinaIncome/V20190101/SouthCarolinaIncome.php, src/Models/Countries/US/SouthCarolina/SouthCarolinaIncomeTaxInformation.php, src/migrations/2020_02_03_000001_add_additional_withholding_to_south_carolina.php, tests/Unit/Countries/US/SouthCarolina/V20190101/SouthCarolinaIncomeTest.php
refs: https://spurjob.atlassian.net/browse/LAWS-117
=> Feature/laws 115 Update sc values and add additional withholding

src/Countries/US/NewJersey/NewJerseyDisabilityInsurance/V20200101/NewJerseyDisabilityInsurance.php, src/Countries/US/NewJersey/NewJerseyFamilyMedicalLeave/V20200101/NewJerseyFamilyMedicalLeave.php, src/Countries/US/NewJersey/NewJerseyUnemploymentInsurance/V20200101/NewJerseyUnemploymentInsurance.php, tests/Unit/Countries/US/NewJersey/V20200101/NewJerseyDisabilityInsuranceTest.php, tests/Unit/Countries/US/NewJersey/V20200101/NewJerseyFamilyMedicalLeaveTest.php, tests/Unit/Countries/US/NewJersey/V20200101/NewJerseyUnemploymentInsuranceTest.php
refs: https://spurjob.atlassian.net/browse/LAWS-120
Note: Not sure if the wage base went up by a lot or if I had the wrong value originally.
=> LAWS-120 NJ updates

src/Countries/US/Illinois/IllinoisIncome/V20200101/IllinoisIncome.php, src/Countries/US/Illinois/IllinoisUnemployment/V20200101/IllinoisUnemployment.php, tests/Unit/Countries/US/Illinois/V20200101/IllinoisIncomeTest.php, tests/Unit/Countries/US/Illinois/V20200101/IllinoisUnemploymentTest.php
refs: https://spurjob.atlassian.net/browse/LAWS-121
=> LAWS-121 IL tax updates

src/Countries/US/Indiana/IndianaIncome/V20190101/IndianaIncome.php, src/Countries/US/Indiana/IndianaLocalIncome.php, tests/Unit/Countries/US/Indiana/V20191001/ClayIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/ClintonIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/DuboisIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/FayetteIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/GreeneIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/HancockIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/HendricksIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/JohnsonIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/OhioIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/OwenIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/PutnamIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/SullivanIncomeTest.php, tests/Unit/Countries/US/Indiana/V20191001/WhitleyIncomeTest.php
refs: https://spurjob.atlassian.net/browse/LAWS-125
=> LAWS-125 updates to Indiana

src/migrations/2020_02_11_000000_update_maryland_income_tax_migration.php
refs: https://spurjob.atlassian.net/browse/LAWS-118
Tasie found a bug with the Maryland name being changed, this corrects that
=> LAWS-118 Update Maryland migration

src/Classes/WorkerTaxes/Payroll.php, src/Countries/US/Missouri/MissouriIncome/V20190101/MissouriIncome.php, src/Models/Countries/US/Missouri/MissouriIncomeTaxInformation.php, src/migrations/2020_02_29_000000_add_parameters_to_missouri_tax_income_information.php, tests/Unit/Countries/US/Missouri/V20190101/MissouriIncomeTest.php
refs: https://spurjob.atlassian.net/browse/LAWS-163
Missouri has a spot on their w4 form for reduced withholding. It is an amount the worker can specify to be withheld instead of our normal calculations.
=> LAWS-163 Missouri Tax Library Changes

src/Countries/US/Kentucky/LudlowCity/V20200101/LudlowCity.php, src/Countries/US/Minnesota/MinnesotaUnemployment/V20200101/MinnesotaUnemployment.php, src/Countries/US/Utah/UtahUnemployment/V20200101/UtahUnemployment.php, tests/Unit/Countries/US/Kentucky/V20200101/local/LudlowCityTest.php, tests/Unit/Countries/US/Minnesota/V20200101/MinnesotaUnemploymentTest.php, tests/Unit/Countries/US/Utah/V20200101/UtahUnemploymentTest.php
These are suta updates for Minnesota and Utah and an occupational tax rate increase for Ludlow City, KY. I combined them into 1 pr because each was only creating 1 new file and 1 new test.
refs: https://spurwork.atlassian.net/browse/LAWS-161
refs: https://spurwork.atlassian.net/browse/LAWS-157
refs: https://spurwork.atlassian.net/browse/LAWS-158
=> LAWS-161 MN and UT SUTA Updates. KY city tax rate increase

src/Countries/US/RhodeIsland/RhodeIslandUnemployment/V20200101/RhodeIslandUnemployment.php, src/config/config.php, tests/Unit/Countries/US/RhodeIsland/V20200101/RhodeIslandUnemploymentTest.php
refs: https://spurwork.atlassian.net/browse/LAWS-149
=> LAWS-149 Rhode Island: Update SUTA Wage Base and New Employer Rates

src/Models/Countries/US/Minnesota/MinnesotaIncomeTaxInformation.php
refs: https://spurwork.atlassian.net/browse/LAWS-197
=> LAWS-197 Fix Minnesota tax library file

src/Countries/US/Nebraska/NebraskaIncome/V20200101/NebraskaIncome.php, src/Models/Countries/US/Nebraska/NebraskaIncomeTaxInformation.php, src/migrations/2020_03_31_000000_add_parameters_to_nebraska_tax_income_information.php, tests/Unit/Countries/US/Nebraska/V20200101/NebraskaIncomeTest.php
refs: https://spurwork.atlassian.net/browse/LAWS-196
This adds additional_withholding. Line 59 is the only line I added or changed in the 2020 NebraskaIncome file from the 2019 file
=> LAWS-196 Nebraska Tax Library Update

src/Countries/US/NewJersey/NewJerseyIncome/V20190101/NewJerseyIncome.php, tests/Unit/Countries/US/NewJersey/V20190101/NewJerseyIncomeTest.php
refs: https://spurwork.atlassian.net/browse/LAWS-211
=> LAWS-211 Bug - New Jersey Tax Rate Table

src/Classes/WorkerTaxes/Payroll.php, src/Classes/WorkerTaxes/TaxManager.php, src/Classes/WorkerTaxes/Taxes.php, src/Countries/US/Delaware/WilmingtonEmployerLicenseFee/V20200101/WilmingtonEmployerLicenseFee.php, src/Countries/US/Delaware/WilmingtonEmployerLicenseFee/WilmingtonEmployerLicenseFee.php, src/Countries/US/Kentucky/CarrollCounty/V20190101/CarrollCounty.php, src/Providers/TaxServiceProvider.php, src/migrations/2020_04_13_000000_add_delaware_wilmington_employer_license_fee.php, tests/Unit/Countries/TaxTestCase.php, tests/Unit/Countries/TestParameters.php, tests/Unit/Countries/TestParametersBuilder.php, tests/Unit/Countries/US/Delaware/V20200101/WilmingtonEmployerLicenseFeeTest.php
refs: https://spurwork.atlassian.net/browse/LAWS-105
=> LAWS-105 Wilmington Employer License Fee

src/Countries/US/Montana/MontanaIncome/V20190101/MontanaIncome.php, src/Models/Countries/US/Montana/MontanaIncomeTaxInformation.php, src/migrations/2020_04_28_000000_add_additional_withholding_to_montana_income_tax_information.php, tests/Unit/Countries/US/Montana/V20190101/MontanaIncomeTest.php
refs: https://spurwork.atlassian.net/browse/LAWS-235
Montana needed additional withholding
=> LAWS-235 Montana Tax Library Updates

src/Countries/US/Michigan/MichiganIncome/V20200101/MichiganIncome.php, tests/Unit/Countries/US/Michigan/V20200101/MichiganIncomeTest.php
refs: https://spurwork.atlassian.net/browse/LAWS-247
=> LAWS-247 Michigan 2020 tax library update

src/Models/Countries/US/Pennsylvania/PennsylvaniaIncomeTaxInformation.php, src/migrations/2020_05_08_000000_add_parameters_to_pennsylvania_income_tax_information.php
refs: https://spurwork.atlassian.net/browse/LAWS-249
Note: This is the PR that goes with the Pennsylvania Residency Form. The data is for local taxes that I have been working on
=> LAWS-249 pa tax library update

src/Classes/WorkerTaxes/Payroll.php, src/Classes/WorkerTaxes/TaxManager.php, src/Countries/US/WestVirginia/CharlestonCityServiceFee/CharlestonCityServiceFee.php, src/Countries/US/WestVirginia/FairmontCityServiceFee/FairmontCityServiceFee.php, src/Countries/US/WestVirginia/FairmontCityServiceFee/V20190101/FairmontCityServiceFee.php, src/Countries/US/WestVirginia/HuntingtonCityServiceFee/HuntingtonCityServiceFee.php, src/Countries/US/WestVirginia/HuntingtonCityServiceFee/V20190101/HuntingtonCityServiceFee.php, src/Countries/US/WestVirginia/MorgantownCityServiceFee/MorgantownCityServiceFee.php, src/Countries/US/WestVirginia/MorgantownCityServiceFee/V20190101/MorgantownCityServiceFee.php, src/Countries/US/WestVirginia/ParkersburgCityServiceFee/ParkersburgCityServiceFee.php, src/Countries/US/WestVirginia/ParkersburgCityServiceFee/V20190101/ParkersburgCityServiceFee.php, tests/Unit/Countries/TaxTestCase.php, tests/Unit/Countries/TestParameters.php, tests/Unit/Countries/TestParametersBuilder.php, tests/Unit/Countries/US/WestVirginia/V20190101/CharlestonCityServiceFeeTest.php, tests/Unit/Countries/US/WestVirginia/V20190101/FairmontCityServiceFeeTest.php, tests/Unit/Countries/US/WestVirginia/V20190101/HuntingtonCityServiceFeeTest.php, tests/Unit/Countries/US/WestVirginia/V20190101/MorgantownCityServiceFeeTest.php, tests/Unit/Countries/US/WestVirginia/V20190101/ParkersburgCityServiceFeeTest.php
refs: https://spurwork.atlassian.net/browse/LAWS-192
=> LAWS-192 West Virginia City Service Fee

src/Countries/US/Indiana/IndianaLocalIncome.php, tests/Unit/Countries/US/Indiana/V20190101/local/VanderburghIncomeTest.php
refs: https://spurwork.atlassian.net/browse/ACC-1092
=> ACC-1092 Indiana Local Income - Default deduction to $0 when exemption > wages earned

src/Countries/US/FederalIncome/FederalIncome.php, src/Countries/US/FederalIncome/V20210101/FederalIncome.php, tests/Unit/Countries/US/FederalIncome/V20210101/FederalIncomeTest.php
[2021 W4 Tax Library Update](https://spurwork.atlassian.net/browse/SS-199)
* implement 2021 federal income tax
=> SS-199 - 2021 federal taxes

src/Countries/US/Pennsylvania/PennsylvaniaLSTTaxEmployer/PennsylvaniaLSTTaxEmployer.php
[PA LST Tax: Set up as Liability and should be withheld from the worker](https://spurwork.atlassian.net/browse/SS-237)
* make PA LST withheld
=> SS-237 - make PA LST withheld

src/Countries/US/Arkansas/ArkansasUnemployment/V20210101/ArkansasUnemployment.php, src/Countries/US/Iowa/IowaUnemployment/V20210101/IowaUnemployment.php, src/Countries/US/Missouri/MissouriUnemployment/V20210101/MissouriUnemployment.php, src/Countries/US/Montana/MontanaUnemployment/V20210101/MontanaUnemployment.php, src/Countries/US/Nevada/NevadaUnemployment/V20210101/NevadaUnemployment.php, src/Countries/US/NewJersey/NewJerseyUnemployment/V20210101/NewJerseyUnemployment.php, src/Countries/US/Oklahoma/OklahomaUnemployment/V20210101/OklahomaUnemployment.php, src/Countries/US/Vermont/VermontUnemployment/V20210101/VermontUnemployment.php, src/Countries/US/Washington/WashingtonUnemployment/V20210101/WashingtonUnemployment.php, src/Countries/US/Wyoming/WyomingUnemployment/V20210101/WyomingUnemployment.php, tests/Unit/Countries/US/Arkansas/V20210101/ArkansasUnemploymentTest.php, tests/Unit/Countries/US/Iowa/V20210101/IowaUnemploymentTest.php, tests/Unit/Countries/US/Missouri/V20210101/MissouriUnemploymentTest.php, tests/Unit/Countries/US/Montana/V20210101/MontanaUnemploymentTest.php, tests/Unit/Countries/US/Nevada/V20210101/NevadaUnemploymentTest.php, tests/Unit/Countries/US/NewJersey/V20210101/NewJerseyUnemploymentTest.php, tests/Unit/Countries/US/Oklahoma/V20210101/OklahomaUnemploymentTest.php, tests/Unit/Countries/US/Vermont/V20210101/VermontUnemploymentTest.php, tests/Unit/Countries/US/Washington/V20210101/WashingtonUnemploymentTest.php, tests/Unit/Countries/US/Wyoming/V20210101/WyomingUnemploymentTest.php
refs: https://spurwork.atlassian.net/browse/ACC-1233
Suta wage base spreadsheet - https://docs.google.com/spreadsheets/d/1lqERDYMgzrzNjZP1ry6q3UWNrJn0iIpdhi8VYOPGXzI/edit#gid=0
=> Feature/acc 1233 Update SUTA wage bases for 2021

src/Countries/US/FederalIncome/V20210101/FederalIncome.php
add federal supplemental tax rate
=> SS-238 - add 2001 federal supplemental rate

composer.json, composer.lock, src/Models/GovernmentalUnitArea.php
[Create nova governmental unit areas page](https://spurwork.atlassian.net/browse/SS-245)
* add postgis info to model
=> SS-245 - nova gua page

composer.lock
[Update laravel](https://spurwork.atlassian.net/browse/SS-274)
* update laravel
=> SS-274 - update laravel

src/Countries/US/SocialSecurity/V20220101/SocialSecurity.php, src/Countries/US/SocialSecurity/V20220101/SocialSecurityEmployer.php, tests/Unit/Countries/US/SocialSecurity/V20220101/SocialSecurityEmployerTest.php, tests/Unit/Countries/US/SocialSecurity/V20220101/SocialSecurityTest.php
[2022 SS Wage Base Change](https://spurwork.atlassian.net/browse/SS-466)
* Update 2022 SS tax
=> SS-466 - 2022 SS wage base
